import KursusRPL from "../assets/image/kursusRPL.jpg";
import KursusDesain from "../assets/image/kursusDesain.jpg";
import KursusAkuntansi from "../assets/image/kursusAkuntansi.jpg";
import KursusOtomotif from "../assets/image/kursusOtomotif.jpg";
import KursusTataboga from "../assets/image/kursusTataboga.jpg";
import KursusEditting from "../assets/image/kursusEditting.jpg";

export const courses = [
  {
    id: 1,
    title: "Web Development dengan React",
    category: "Rekayasa Perangkat Lunak",
    level: "Pemula",
    rating: 4.9,
    students: "1.2k",
    duration: "24 jam",
    sessions: "12 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Pelajari cara membangun aplikasi web modern menggunakan React. Mulai dari dasar hingga deploy project nyata.",
    mentor: "Budi Santoso",
    price: "Rp 180.000",
    badge: "Terlaris",
    online: true,
    image: KursusRPL,
    accent: "#185FA5",
    accentRgb: "24,95,165",
  },
  {
    id: 2,
    title: "Desain UI/UX Profesional",
    category: "Desain Grafis",
    level: "Menengah",
    rating: 4.8,
    students: "980",
    duration: "18 jam",
    sessions: "10 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Kuasai Figma dan prinsip desain UI/UX dari nol. Buat portofolio desain yang siap kerja.",
    mentor: "Sari Dewi",
    price: "Rp 150.000",
    badge: "Populer",
    online: true,
    image: KursusDesain,
    accent: "#993356",
    accentRgb: "153,51,86",
  },
  {
    id: 3,
    title: "Akuntansi Digital & Excel",
    category: "Akuntansi",
    level: "Pemula",
    rating: 4.7,
    students: "2.1k",
    duration: "20 jam",
    sessions: "8 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Kuasai pembukuan digital dan Excel untuk kebutuhan akuntansi modern di dunia kerja.",
    mentor: "Rina Marlina",
    price: "Rp 120.000",
    badge: "Terlaris",
    online: true,
    image: KursusAkuntansi,
    accent: "#0F6E56",
    accentRgb: "15,110,86",
  },
  {
    id: 4,
    title: "Teknik Perawatan Mesin",
    category: "Teknik Otomotif",
    level: "Menengah",
    rating: 4.8,
    students: "760",
    duration: "30 jam",
    sessions: "15 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Pelajari teknik servis dan perawatan mesin kendaraan dari mekanik berpengalaman.",
    mentor: "Doni Prasetyo",
    price: "Rp 200.000",
    badge: "Baru",
    online: false,
    image: KursusOtomotif,
    accent: "#854F0B",
    accentRgb: "133,79,11",
  },
  {
    id: 5,
    title: "Editing Video & Motion",
    category: "Multimedia",
    level: "Pemula",
    rating: 4.9,
    students: "1.5k",
    duration: "22 jam",
    sessions: "11 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Kuasai Adobe Premiere dan After Effects untuk editing video profesional dan motion graphic.",
    mentor: "Fajar Nugroho",
    price: "Rp 165.000",
    badge: "Populer",
    online: true,
    image: KursusEditting,
    accent: "#534AB7",
    accentRgb: "83,74,183",
  },
  {
    id: 6,
    title: "Pastry & Bakery Modern",
    category: "Tata Boga",
    level: "Pemula",
    rating: 4.6,
    students: "640",
    duration: "16 jam",
    sessions: "8 Pertemuan",
    ageRange: "15–18 tahun",
    desc: "Belajar membuat kue dan roti modern dari chef berpengalaman. Cocok untuk pemula.",
    mentor: "Chef Maya",
    price: "Rp 135.000",
    badge: "Online",
    online: true,
    image: KursusTataboga,
    accent: "#993C1D",
    accentRgb: "153,60,29",
  },
];

export function getCourseById(id) {
  return courses.find((c) => String(c.id) === String(id));
}